AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  transcribe-from-s3

  Sample SAM Template for transcribe-from-s3

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TranscribeFromS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: transcribe/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
  SrcBucket:
    Type: AWS::S3::Bucket
  TgtBucket:
    Type: AWS::S3::Bucket

Outputs:
  TranscribeFromS3Function:
    Description: "Transcribe From S3 Lambda Function ARN"
    Value: !GetAtt TranscribeFromS3Function.Arn
  TranscribeFromS3FunctionIamRole:
    Description: "Implicit IAM Role created for Transcribe From S3 function"
    Value: !GetAtt   TranscribeFromS3FunctionRole.Arn
